"""
SEO PUBLISHER BOT

What it does:
  1. Picks up articles generated by Content Generator Bot
  2. Publishes each article to Medium, Dev.to, and Hashnode (all FREE)
  3. Marks each article as published so it's never duplicated
  4. Tracks all published URLs for the dashboard

Run schedule: Every 24 hours (via GitHub Actions)
Free APIs used:
  • Medium Integration Token (https://medium.com/me/settings)
  • Dev.to API Key (https://dev.to/settings/extensions)
  • Hashnode Access Token (https://hashnode.com/settings/developer)
"""

import json
import time
import os
import requests

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from bots.base_bot import BaseBot
from bots.content_generator import ContentGeneratorBot
import state_manager as sm


class SeoPublisherBot(BaseBot):

    def __init__(self):
        super().__init__("seo_publisher")

    # ─────────────────────────────────────────────────────────────
    #  Main logic
    # ─────────────────────────────────────────────────────────────

    def run(self):
        articles = ContentGeneratorBot.get_pending_articles()

        if not articles:
            self.log.info("No pending articles. Content Generator hasn't run yet.")
            return

        unpublished = [a for a in articles if not a.get("published")]
        self.log.info(f"Found {len(unpublished)} unpublished articles.")

        for article in unpublished:
            title = article["title"]
            self.log.info(f"Publishing: {title[:60]}...")
            self.checkpoint("before_publish", {"title": title})

            results = {}

            # Try each platform — skip if API key not set
            if os.getenv("MEDIUM_TOKEN"):
                results["medium"] = self._publish_to_medium(article)
                time.sleep(2)

            if os.getenv("DEVTO_API_KEY"):
                results["devto"] = self._publish_to_devto(article)
                time.sleep(2)

            if os.getenv("HASHNODE_TOKEN") and os.getenv("HASHNODE_PUBLICATION_ID"):
                results["hashnode"] = self._publish_to_hashnode(article)
                time.sleep(2)

            if not results:
                self.log.warning("No publishing API keys set. Add them to .env to start publishing.")
                self.log.info("Articles are still saved in the database — add keys anytime.")
                break

            # Mark as published
            for platform, url in results.items():
                if url:
                    sm.mark_url_published(url, platform, title)
                    self.log.info(f"  ✅ {platform}: {url}")

            ContentGeneratorBot.mark_article_published(title)
            self.save("last_published", {"title": title, "platforms": list(results.keys())})

    # ─────────────────────────────────────────────────────────────
    #  Medium Publisher
    # ─────────────────────────────────────────────────────────────

    def _publish_to_medium(self, article: dict) -> str:
        """Publish to Medium. Returns the article URL or empty string."""
        token = os.getenv("MEDIUM_TOKEN", "")
        try:
            # Get author ID
            user_resp = requests.get(
                "https://api.medium.com/v1/me",
                headers={"Authorization": f"Bearer {token}"}
            )
            user_resp.raise_for_status()
            author_id = user_resp.json()["data"]["id"]

            # Publish
            payload = {
                "title":         article["title"],
                "contentFormat": "markdown",
                "content":       article["body"],
                "tags":          article.get("keywords", [])[:5],
                "publishStatus": "public",
                "canonicalUrl":  article.get("site", "")
            }
            resp = requests.post(
                f"https://api.medium.com/v1/users/{author_id}/posts",
                headers={"Authorization": f"Bearer {token}",
                         "Content-Type": "application/json"},
                json=payload
            )
            resp.raise_for_status()
            return resp.json()["data"]["url"]
        except Exception as e:
            self.log.error(f"Medium publish failed: {e}")
            return ""

    # ─────────────────────────────────────────────────────────────
    #  Dev.to Publisher
    # ─────────────────────────────────────────────────────────────

    def _publish_to_devto(self, article: dict) -> str:
        """Publish to Dev.to. Returns the article URL or empty string."""
        api_key = os.getenv("DEVTO_API_KEY", "")
        try:
            payload = {
                "article": {
                    "title":        article["title"],
                    "body_markdown": article["body"],
                    "published":    True,
                    "tags":         [k.replace(" ", "").lower() for k in article.get("keywords", [])[:4]],
                    "description":  article.get("meta_desc", ""),
                    "canonical_url": article.get("site", "")
                }
            }
            resp = requests.post(
                "https://dev.to/api/articles",
                headers={"api-key": api_key, "Content-Type": "application/json"},
                json=payload
            )
            resp.raise_for_status()
            return resp.json().get("url", "")
        except Exception as e:
            self.log.error(f"Dev.to publish failed: {e}")
            return ""

    # ─────────────────────────────────────────────────────────────
    #  Hashnode Publisher
    # ─────────────────────────────────────────────────────────────

    def _publish_to_hashnode(self, article: dict) -> str:
        """Publish to Hashnode. Returns the article URL or empty string."""
        token  = os.getenv("HASHNODE_TOKEN", "")
        pub_id = os.getenv("HASHNODE_PUBLICATION_ID", "")
        try:
            # Convert markdown body to basic HTML for Hashnode
            content = article["body"]
            query = """
            mutation PublishPost($input: PublishPostInput!) {
              publishPost(input: $input) {
                post { url }
              }
            }"""
            variables = {
                "input": {
                    "title":         article["title"],
                    "contentMarkdown": content,
                    "publicationId": pub_id,
                    "tags":          [],
                    "metaTags": {
                        "description": article.get("meta_desc", "")
                    }
                }
            }
            resp = requests.post(
                "https://gql.hashnode.com",
                headers={"Authorization": token, "Content-Type": "application/json"},
                json={"query": query, "variables": variables}
            )
            resp.raise_for_status()
            data = resp.json()
            if "errors" in data:
                raise RuntimeError(data["errors"])
            return data["data"]["publishPost"]["post"]["url"]
        except Exception as e:
            self.log.error(f"Hashnode publish failed: {e}")
            return ""


# ── Run directly ──────────────────────────────────────────────────

if __name__ == "__main__":
    bot = SeoPublisherBot()
    bot.execute()
